apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "3000"
  JWT_EXPIRES_IN: "1d"
  DB_HOST: "pg-bursting-demo.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "stockdb"
